apiVersion: v1
kind: Service
metadata:
  name: student-event-platform-service
spec:
  type: LoadBalancer # Expose to the internet (or NodePort for local)
  selector:
    app: student-event-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
