apiVersion: v1
kind: Service
metadata:
  name: student-event-platform-service
spec:
  type: NodePort
  selector:
    app: student-event-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
